/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samarth
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        AddBtn = new javax.swing.JButton();
        SortBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dish Management");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        setMinimumSize(new java.awt.Dimension(1350, 772));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Desktop.setPreferredSize(new java.awt.Dimension(1350, 710));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 1350, 710));

        AddBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(0, 0, 102));
        AddBtn.setText("ADD");
        AddBtn.setBorder(null);
        AddBtn.setContentAreaFilled(false);
        AddBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        AddBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        AddBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 40));

        SortBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        SortBtn.setForeground(new java.awt.Color(0, 0, 102));
        SortBtn.setText("Sort");
        SortBtn.setBorder(null);
        SortBtn.setContentAreaFilled(false);
        SortBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        SortBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        SortBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        SortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SortBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 130, 40));

        SearchBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(0, 0, 102));
        SearchBtn.setText("Search");
        SearchBtn.setBorder(null);
        SearchBtn.setContentAreaFilled(false);
        SearchBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        SearchBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        SearchBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 130, 40));

        ViewBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ViewBtn.setForeground(new java.awt.Color(0, 0, 102));
        ViewBtn.setText("View");
        ViewBtn.setBorder(null);
        ViewBtn.setContentAreaFilled(false);
        ViewBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        ViewBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        ViewBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 130, 40));

        UpdateBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(0, 0, 102));
        UpdateBtn.setText("UPDATE");
        UpdateBtn.setBorder(null);
        UpdateBtn.setContentAreaFilled(false);
        UpdateBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        UpdateBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        UpdateBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 130, 40));

        DeleteBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(0, 0, 102));
        DeleteBtn.setText("DELETE");
        DeleteBtn.setBorder(null);
        DeleteBtn.setContentAreaFilled(false);
        DeleteBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        DeleteBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        DeleteBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 130, 40));

        ExitBtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(0, 0, 102));
        ExitBtn.setText("EXIT");
        ExitBtn.setBorder(null);
        ExitBtn.setContentAreaFilled(false);
        ExitBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        ExitBtn.setMinimumSize(new java.awt.Dimension(85, 23));
        ExitBtn.setPreferredSize(new java.awt.Dimension(85, 23));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 130, 40));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        Add a = new Add();
        this.Desktop.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_AddBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        Search srch = new Search();
        this.Desktop.add(srch);
        srch.setVisible(true);
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        View v = new View();
        this.Desktop.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        Update u = new Update();
        this.Desktop.add(u);
        u.setVisible(true);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        Delete del = new Delete();
        this.Desktop.add(del);
        del.setVisible(true);
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void SortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortBtnActionPerformed
        // TODO add your handling code here:
        Sort srt = new Sort();
        this.Desktop.add(srt);
        srt.setVisible(true);
    }//GEN-LAST:event_SortBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton SortBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
